import React, { useState } from 'react';
import { 
  User, 
  Home, 
  Hash, 
  Minus, 
  Plus, 
  IndianRupee, 
  CheckCircle2, 
  Clock, 
  Save, 
  ArrowLeft,
  ChevronDown,
  Calendar
} from 'lucide-react';
import type { LaundryOrder } from './LaundryPage';

interface CreateLaundryOrderPageProps {
  onSaveOrder: (newOrder: LaundryOrder) => void;
  onCancel: () => void;
  showToast?: (msg: string) => void;
  nextOrderIdNumber?: number;
}

export const mockStudentsList = [
  { name: 'Aarav Sharma', room: 'Room 101', block: 'Block A Hostel' },
  { name: 'Kabir Verma', room: 'Room 204', block: 'Block A Hostel' },
  { name: 'Ishaan Gupta', room: 'Room 112', block: 'Block B Hostel' },
  { name: 'Ananya Roy', room: 'Room 305', block: 'Block B Hostel' },
  { name: 'Rohan Mehta', room: 'Room 108', block: 'Block C Hostel' },
  { name: 'Vijay Sai', room: 'Room 101', block: 'Block A Hostel' },
  { name: 'Rohit Arjun', room: 'Room 102', block: 'Block A Hostel' },
  { name: 'Pranathi Sharma', room: 'Room 201', block: 'Block B Hostel' },
  { name: 'Ankit Kumar', room: 'Room 202', block: 'Block B Hostel' },
  { name: 'Sai Meghana', room: 'Room 301', block: 'Block C Hostel' }
];

export const CreateLaundryOrderPage: React.FC<CreateLaundryOrderPageProps> = ({
  onSaveOrder,
  onCancel,
  showToast,
  nextOrderIdNumber = 106
}) => {
  const autoGeneratedOrderId = `LDR-00${nextOrderIdNumber}`;

  // Form State
  const [studentName, setStudentName] = useState('');
  const [selectedRoom, setSelectedRoom] = useState('Room 101');
  const [selectedBlock, setSelectedBlock] = useState('Block A Hostel');
  const [itemsCount, setItemsCount] = useState<number>(0);
  const [costPerItem] = useState<number>(10);
  const [paymentStatus, setPaymentStatus] = useState<'Pending' | 'Paid'>('Pending');
  const [progressStage, setProgressStage] = useState<'Pending' | 'Washing' | 'Ready' | 'Delivered'>('Pending');
  const [assignedStaff, setAssignedStaff] = useState('Rita Devi');
  const [expectedDeliveryDate, setExpectedDeliveryDate] = useState('2026-06-30');

  // Auto-fill room when student is selected from dropdown
  const handleStudentSelect = (name: string) => {
    setStudentName(name);
    const found = mockStudentsList.find(s => s.name.toLowerCase() === name.toLowerCase());
    if (found) {
      setSelectedRoom(found.room);
      setSelectedBlock(found.block);
    }
  };

  const handleIncrementItems = () => {
    setItemsCount(prev => prev + 1);
  };

  const handleDecrementItems = () => {
    setItemsCount(prev => (prev > 0 ? prev - 1 : 0));
  };

  const estimatedCost = (itemsCount * costPerItem).toFixed(2);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!studentName.trim()) {
      if (showToast) showToast('Please select or enter a student name');
      return;
    }

    if (itemsCount <= 0) {
      if (showToast) showToast('Please add at least 1 item to the order');
      return;
    }

    const staffAvatar = assignedStaff === 'Rita Devi'
      ? 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80'
      : 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80';

    const newOrder: LaundryOrder = {
      id: 'ldr_' + Date.now(),
      orderId: autoGeneratedOrderId,
      residentName: studentName.trim(),
      roomNumber: selectedRoom.replace('Room ', ''),
      hostelBlock: selectedBlock,
      itemsCount: itemsCount,
      itemsDetail: `${itemsCount} Mixed Garments`,
      staffName: assignedStaff,
      staffAvatar: staffAvatar,
      status: progressStage,
      paymentStatus: paymentStatus,
      amount: parseFloat(estimatedCost) || (itemsCount * 10),
      expectedDelivery: `${expectedDeliveryDate}, Scheduled`
    };

    onSaveOrder(newOrder);
  };

  return (
    <div className="create-laundry-page-wrapper">
      {/* Top Page Header */}
      <div className="create-laundry-top-header">
        
        <h2 className="create-laundry-title">Create Laundry Order</h2>
      </div>

      <form onSubmit={handleSubmit} className="create-laundry-form">
        {/* SECTION 1: ORDER IDENTIFICATION */}
        <div className="create-section-container">
          <div className="create-section-header">
            <div className="section-title-left">
              <span className="blue-bar-indicator" />
              <span className="section-title-txt">Order Identification</span>
            </div>
            <span className="order-id-read-pill">{autoGeneratedOrderId}</span>
          </div>

          <div className="create-section-card">
            {/* Student Name */}
            <div className="create-field-group">
              <label className="create-field-label">
                <User size={13} className="label-icon" /> STUDENT NAME
              </label>
              <div className="student-select-input-wrapper">
                <input 
                  type="text"
                  className="create-text-input"
                  placeholder="Enter full name"
                  value={studentName}
                  onChange={(e) => handleStudentSelect(e.target.value)}
                  list="students-datalist"
                />
                <datalist id="students-datalist">
                  {mockStudentsList.map((s, idx) => (
                    <option key={idx} value={s.name}>{s.room} ({s.block})</option>
                  ))}
                </datalist>
              </div>
            </div>

            {/* Room/Hostel & Order ID (Ref) Row */}
            <div className="create-two-cols">
              <div className="create-field-group">
                <label className="create-field-label">
                  <Home size={13} className="label-icon" /> ROOM / HOSTEL
                </label>
                <div className="create-select-wrapper">
                  <select 
                    className="create-select-input"
                    value={selectedRoom}
                    onChange={(e) => setSelectedRoom(e.target.value)}
                  >
                    <option value="Room 101">Room 101</option>
                    <option value="Room 102">Room 102</option>
                    <option value="Room 108">Room 108</option>
                    <option value="Room 112">Room 112</option>
                    <option value="Room 201">Room 201</option>
                    <option value="Room 202">Room 202</option>
                    <option value="Room 204">Room 204</option>
                    <option value="Room 301">Room 301</option>
                    <option value="Room 305">Room 305</option>
                  </select>
                  <ChevronDown size={15} className="select-arrow-muted" />
                </div>
              </div>

              <div className="create-field-group">
                <label className="create-field-label">
                  <Hash size={13} className="label-icon" /> ORDER ID (REF)
                </label>
                <input 
                  type="text"
                  disabled
                  className="create-text-input disabled-input"
                  value={autoGeneratedOrderId}
                />
              </div>
            </div>
          </div>
        </div>

        {/* SECTION 2: GARMENT DETAILS */}
        <div className="create-section-container">
          <div className="create-section-header">
            <div className="section-title-left">
              <span className="blue-bar-indicator" />
              <span className="section-title-txt">Garment Details</span>
            </div>
          </div>

          <div className="create-section-card">
            {/* Total Items Light Blue Inner Box */}
            <div className="total-items-inner-box">
              <div className="total-items-left">
                <span className="items-box-label">TOTAL ITEMS</span>
                <span className="items-box-val">{itemsCount}</span>
              </div>

              <div className="items-counter-controls">
                <button 
                  type="button" 
                  className="counter-btn minus-btn"
                  onClick={handleDecrementItems}
                  aria-label="Decrement item count"
                >
                  <Minus size={16} />
                </button>

                <button 
                  type="button" 
                  className="counter-btn plus-btn"
                  onClick={handleIncrementItems}
                  aria-label="Increment item count"
                >
                  <Plus size={16} />
                </button>
              </div>
            </div>

            {/* Estimated Cost Field */}
            <div className="create-field-group" style={{ marginTop: '14px' }}>
              <label className="create-field-label">
                <IndianRupee size={13} className="label-icon" /> ESTIMATED COST
              </label>
              <div className="cost-input-wrapper">
                <span className="rupee-prefix">₹</span>
                <input 
                  type="text"
                  readOnly
                  className="create-text-input cost-input"
                  value={estimatedCost}
                />
              </div>
            </div>
          </div>
        </div>

        {/* SECTION 3: WORKFLOW STATUS */}
        <div className="create-section-container">
          <div className="create-section-header">
            <div className="section-title-left">
              <span className="blue-bar-indicator" />
              <span className="section-title-txt">Workflow Status</span>
            </div>
          </div>

          <div className="create-section-card">
            {/* Row 1: Payment Status & Progress Stage */}
            <div className="create-two-cols">
              <div className="create-field-group">
                <label className="create-field-label">
                  <CheckCircle2 size={13} className="label-icon" /> PAYMENT STATUS
                </label>
                <div className="create-select-wrapper">
                  <select 
                    className={`create-select-input payment-status-select ${paymentStatus.toLowerCase()}`}
                    value={paymentStatus}
                    onChange={(e) => setPaymentStatus(e.target.value as 'Pending' | 'Paid')}
                  >
                    <option value="Pending">Pending</option>
                    <option value="Paid">Paid</option>
                  </select>
                  <ChevronDown size={15} className="select-arrow-muted" />
                </div>
              </div>

              <div className="create-field-group">
                <label className="create-field-label">
                  <Clock size={13} className="label-icon" /> PROGRESS STAGE
                </label>
                <div className="create-select-wrapper">
                  <select 
                    className="create-select-input"
                    value={progressStage}
                    onChange={(e) => setProgressStage(e.target.value as any)}
                  >
                    <option value="Pending">Pending</option>
                    <option value="Washing">Washing</option>
                    <option value="Ready">Ready</option>
                    <option value="Delivered">Delivered</option>
                  </select>
                  <ChevronDown size={15} className="select-arrow-muted" />
                </div>
              </div>
            </div>

            {/* Row 2: Assigned Staff */}
            <div className="create-field-group" style={{ marginTop: '12px' }}>
              <label className="create-field-label">
                <User size={13} className="label-icon" /> ASSIGNED STAFF
              </label>
              <div className="create-select-wrapper staff-select-wrapper">
                <div className="staff-avatar-prefix">
                  <img 
                    src={assignedStaff === 'Rita Devi'
                      ? 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80'
                      : 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80'}
                    alt={assignedStaff}
                    className="staff-select-img"
                  />
                </div>
                <select 
                  className="create-select-input staff-select-input"
                  value={assignedStaff}
                  onChange={(e) => setAssignedStaff(e.target.value)}
                >
                  <option value="Rita Devi">Rita Devi</option>
                  <option value="Shyam Singh">Shyam Singh</option>
                </select>
                <ChevronDown size={15} className="select-arrow-muted" />
              </div>
            </div>

            {/* Row 3: Expected Delivery Date */}
            <div className="create-field-group" style={{ marginTop: '12px' }}>
              <label className="create-field-label">
                <Calendar size={13} className="label-icon" /> EXPECTED DELIVERY
              </label>
              <div className="date-input-wrapper">
                <Calendar size={15} className="date-icon-prefix" />
                <input 
                  type="date"
                  className="create-text-input date-input"
                  value={expectedDeliveryDate}
                  onChange={(e) => setExpectedDeliveryDate(e.target.value)}
                />
              </div>
            </div>
          </div>
        </div>

        {/* SECTION 4: ACTIONS */}
        <div className="create-actions-section">
          <button type="submit" className="save-order-submit-btn">
            <Save size={18} />
            <span>Save Order</span>
          </button>

          <button 
            type="button" 
            className="discard-entry-btn"
            onClick={onCancel}
          >
            Discard Entry
          </button>
        </div>
      </form>
    </div>
  );
};

export default CreateLaundryOrderPage;
