import type { 
  WeeklyMenu, 
  PantryItem, 
  KitchenExpense, 
  Supplier,
  HostelStat,
  FloorOccupancy,
  HostelAnnouncement,
  HostelRoom,
  ResidentRequest,
  FeeTransaction,
  ActivityItem
} from './types';

export const initialWeeklyMenu: WeeklyMenu = {
  Monday: {
    breakfast: 'Idli Sambar',
    lunch: 'Roti, Dal, Paneer, Rice',
    snacks: 'Samosa, Tea',
    dinner: 'Aloo Gobi, Roti, Rice',
  },
  Tuesday: {
    breakfast: 'Aloo Paratha',
    lunch: 'Veg Biryani, Raita',
    snacks: 'Pakoda, Coffee',
    dinner: 'Dal Tadka, Roti, Rice',
  },
  Wednesday: {
    breakfast: 'Poha',
    lunch: 'Rajma Chawal, Salad',
    snacks: 'Sandwich, Tea',
    dinner: 'Mix Veg, Roti, Rice',
  },
  Thursday: {
    breakfast: 'Bread Toast, Eggs',
    lunch: 'Chole Bhature, Rice',
    snacks: 'Biscuits, Tea',
    dinner: 'Kadhi Chawal, Roti',
  },
  Friday: {
    breakfast: 'Uttapam, Chutney',
    lunch: 'Egg Curry, Rice, Roti',
    snacks: 'Kachori, Tea',
    dinner: 'Bhindi Masala, Roti, Rice',
  },
  Saturday: {
    breakfast: 'Puri Sabji',
    lunch: 'Khichdi, Papad, Dahi',
    snacks: 'Maggi, Tea',
    dinner: 'Paneer Bhurji, Roti',
  },
  Sunday: {
    breakfast: 'Chole Bhature',
    lunch: 'Special Veg Thali, Rice',
    snacks: 'Pav Bhaji, Tea',
    dinner: 'Dal Makhani, Butter Roti',
  },
};

export const initialPantryItems: PantryItem[] = [
  {
    id: 'p1',
    name: 'Amul Milk',
    unit: 'Liters',
    price: 60,
    stock: 12,
    threshold: 20,
    supplier: 'Mother Dairy Local',
  },
  {
    id: 'p2',
    name: 'Fresh Eggs',
    unit: 'pcs',
    price: 7,
    stock: 150,
    threshold: 50,
    supplier: 'Poultry Farm Direct',
  },
  {
    id: 'p3',
    name: 'Paneer (Cottage Cheese)',
    unit: 'kg',
    price: 320,
    stock: 5,
    threshold: 10,
    supplier: 'Amul Distributor',
  },
  {
    id: 'p4',
    name: 'Wheat Flour (Atta)',
    unit: 'kg',
    price: 40,
    stock: 120,
    threshold: 50,
    supplier: 'Anaj Bhandar Wholesale',
  },
  {
    id: 'p5',
    name: 'Cooking Oil',
    unit: 'Liters',
    price: 140,
    stock: 15,
    threshold: 30,
    supplier: 'Aggarwal Provision Store',
  },
];

export const initialExpenses: KitchenExpense[] = [
  {
    id: 'e1',
    date: '2026-07-25',
    category: 'Grocery / Grains',
    description: 'Purchased 120kg wheat flour and spices',
    amount: 4800,
    status: 'Paid',
  },
  {
    id: 'e2',
    date: '2026-07-24',
    category: 'Dairy',
    description: 'Weekly milk and paneer procurement',
    amount: 2400,
    status: 'Paid',
  },
  {
    id: 'e3',
    date: '2026-07-22',
    category: 'Eggs / Poultry',
    description: 'Egg crates from farm',
    amount: 1050,
    status: 'Paid',
  },
  {
    id: 'e4',
    date: '2026-07-20',
    category: 'Veggies / Fruits',
    description: 'Fresh vegetables and onions',
    amount: 1500,
    status: 'Paid',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 's1',
    name: 'Anaj Bhandar Wholesale',
    contactPerson: 'Vikram Gupta',
    phone: '+91 99881 22334',
    itemsSupplied: 'Wheat Flour, Rice, Pulses, Spices',
    address: 'Shop #14, Grain Market, Sector 12, City',
    lastDeliveryDate: '2026-07-25',
    paymentStatus: 'Paid',
  },
  {
    id: 's2',
    name: 'Mother Dairy Local',
    contactPerson: 'Ramesh Kumar',
    phone: '+91 99883 44556',
    itemsSupplied: 'Fresh Milk, Curd, Butter, Paneer',
    address: 'Booth #8, Dairy Complex, Main Road',
    lastDeliveryDate: '2026-07-28',
    paymentStatus: 'Pending',
  },
  {
    id: 's3',
    name: 'Poultry Farm Direct',
    contactPerson: 'Suresh Patel',
    phone: '+91 99884 55667',
    itemsSupplied: 'Farm Fresh Eggs',
    address: 'Village Farm Outlet, NH-44 Bypass',
    lastDeliveryDate: '2026-07-22',
    paymentStatus: 'Paid',
  },
  {
    id: 's4',
    name: 'Aggarwal Provision Store',
    contactPerson: 'Sanjay Aggarwal',
    phone: '+91 99882 33445',
    itemsSupplied: 'Edible Oils, Packaged Condiments, Tea',
    address: 'Store #4, Central Market, City',
    lastDeliveryDate: '2026-07-15',
    paymentStatus: 'Overdue',
  },
  {
    id: 's5',
    name: 'Green Leaf Mandi Traders',
    contactPerson: 'Arun Yadav',
    phone: '+91 99885 66778',
    itemsSupplied: 'Fresh Vegetables, Onions, Potatoes, Tomatoes',
    address: 'Shop #42, Sabzi Mandi, Main Market',
    lastDeliveryDate: '2026-08-05',
    paymentStatus: 'Paid',
  },
  {
    id: 's6',
    name: 'Fresh Fruits Suppliers',
    contactPerson: 'Mohammad Tariq',
    phone: '+91 99886 77889',
    itemsSupplied: 'Seasonal Fruits, Bananas, Apples, Oranges',
    address: 'Stall #12, Fruit Market Hub',
    lastDeliveryDate: '2026-08-06',
    paymentStatus: 'Pending',
  },
];

// Hostel Management Dashboard Data
export const initialHostelStats: HostelStat = {
  totalHostels: 3,
  totalRooms: 42,
  totalBeds: 110,
  occupiedBeds: 96,
  vacantBeds: 14,
  totalResidents: 96,
  pendingRequests: 8,
  todayCheckIns: 3,
  todayCheckOuts: 1,
  monthlyRevenue: 542000,
  collectedRevenue: 415000,
  pendingRevenue: 127000,
};

export const initialFloorOccupancy: FloorOccupancy[] = [
  { floor: '1st Floor', totalBeds: 36, occupiedBeds: 34, percentage: 94 },
  { floor: '2nd Floor', totalBeds: 38, occupiedBeds: 31, percentage: 82 },
  { floor: '3rd Floor', totalBeds: 36, occupiedBeds: 31, percentage: 86 },
];

export const initialAnnouncements: HostelAnnouncement[] = [
  {
    id: 'ann-1',
    title: 'Water Supply Maintenance Schedule',
    category: 'Maintenance',
    date: '2026-07-28',
    author: 'Warden Rajesh',
    content: 'Water supply to Block B will be temporarily turned off on Sunday from 10:00 AM to 1:00 PM for overhead tank cleaning.',
    pinned: true,
  },
  {
    id: 'ann-2',
    title: 'Special Sunday Mess Feast & Timing',
    category: 'Food & Mess',
    date: '2026-07-27',
    author: 'Mess Committee',
    content: 'Special Veg Thali with Paneer Tikka & Gulab Jamun will be served this Sunday. Dinner timings extended till 10:00 PM.',
    pinned: true,
  },
  {
    id: 'ann-3',
    title: 'Hostel Study Room Hours Extended',
    category: 'General',
    date: '2026-07-26',
    author: 'Student Warden',
    content: 'In view of upcoming university examinations, 2nd Floor Study Room will remain open 24/7 with high-speed Wi-Fi.',
    pinned: false,
  },
];

export const initialHostelRooms: HostelRoom[] = [
  {
    id: 'r101',
    roomNumber: '101',
    floor: '1st Floor',
    sharingType: 'Double Attached',
    status: 'Occupied',
    totalBeds: 2,
    occupiedBeds: 2,
    vacantBeds: 0,
    rentPerMonth: 6500,
    facilities: ['Attached Bath', 'Balcony', 'Study Desks', 'Wi-Fi'],
    residents: [
      { name: 'Amit Verma', phone: '+91 98765 43210', checkInDate: '2025-08-10', course: 'B.Tech CSE' },
      { name: 'Siddharth Rao', phone: '+91 98765 43211', checkInDate: '2025-08-12', course: 'B.Tech ECE' },
    ],
  },
  {
    id: 'r102',
    roomNumber: '102',
    floor: '1st Floor',
    sharingType: 'Double Attached',
    status: 'Partially Occupied',
    totalBeds: 2,
    occupiedBeds: 1,
    vacantBeds: 1,
    rentPerMonth: 6500,
    facilities: ['Attached Bath', 'Wi-Fi', 'Wardrobe'],
    residents: [
      { name: 'Rohan Sharma', phone: '+91 98765 43212', checkInDate: '2025-09-01', course: 'B.Com Hons' },
    ],
  },
  {
    id: 'r103',
    roomNumber: '103',
    floor: '1st Floor',
    sharingType: 'Single AC',
    status: 'Occupied',
    totalBeds: 1,
    occupiedBeds: 1,
    vacantBeds: 0,
    rentPerMonth: 9500,
    facilities: ['AC', 'Attached Bath', 'Study Desk', 'Wi-Fi'],
    residents: [
      { name: 'Dr. Ananya Roy', phone: '+91 98765 43213', checkInDate: '2026-01-05', course: 'M.Tech AI' },
    ],
  },
  {
    id: 'r104',
    roomNumber: '104',
    floor: '1st Floor',
    sharingType: 'Triple Shared',
    status: 'Occupied',
    totalBeds: 3,
    occupiedBeds: 3,
    vacantBeds: 0,
    rentPerMonth: 5000,
    facilities: ['Common Bath', 'Wi-Fi', 'Lockers'],
    residents: [
      { name: 'Kabir Das', phone: '+91 98765 43214', checkInDate: '2025-08-15', course: 'B.Sc Physics' },
      { name: 'Nikhil Mehta', phone: '+91 98765 43215', checkInDate: '2025-08-16', course: 'B.Sc Chem' },
      { name: 'Yash Paul', phone: '+91 98765 43216', checkInDate: '2025-08-20', course: 'B.Sc Math' },
    ],
  },
  {
    id: 'r201',
    roomNumber: '201',
    floor: '2nd Floor',
    sharingType: 'Single AC',
    status: 'Vacant',
    totalBeds: 1,
    occupiedBeds: 0,
    vacantBeds: 1,
    rentPerMonth: 9500,
    facilities: ['AC', 'Attached Bath', 'Balcony', 'Wi-Fi'],
    residents: [],
  },
  {
    id: 'r202',
    roomNumber: '202',
    floor: '2nd Floor',
    sharingType: 'Double Attached',
    status: 'Occupied',
    totalBeds: 2,
    occupiedBeds: 2,
    vacantBeds: 0,
    rentPerMonth: 6500,
    facilities: ['Attached Bath', 'Wi-Fi', 'Study Lamp'],
    residents: [
      { name: 'Aditya Patel', phone: '+91 98765 43217', checkInDate: '2025-08-11', course: 'MBA Marketing' },
      { name: 'Varun Dhawan', phone: '+91 98765 43218', checkInDate: '2025-08-14', course: 'MBA Finance' },
    ],
  },
  {
    id: 'r203',
    roomNumber: '203',
    floor: '2nd Floor',
    sharingType: '4-Sharing',
    status: 'Partially Occupied',
    totalBeds: 4,
    occupiedBeds: 3,
    vacantBeds: 1,
    rentPerMonth: 4200,
    facilities: ['Common Bath', 'Wi-Fi', 'Lockers'],
    residents: [
      { name: 'Kunal Shah', phone: '+91 98765 43219', checkInDate: '2025-09-10', course: 'BCA' },
      { name: 'Manish Goel', phone: '+91 98765 43220', checkInDate: '2025-09-11', course: 'BCA' },
      { name: 'Deepak Joshi', phone: '+91 98765 43221', checkInDate: '2025-09-15', course: 'MCA' },
    ],
  },
  {
    id: 'r204',
    roomNumber: '204',
    floor: '2nd Floor',
    sharingType: 'Double Attached',
    status: 'Maintenance',
    totalBeds: 2,
    occupiedBeds: 0,
    vacantBeds: 2,
    rentPerMonth: 6500,
    facilities: ['Plumbing Overhaul', 'Paint Touchup'],
    residents: [],
  },
  {
    id: 'r301',
    roomNumber: '301',
    floor: '3rd Floor',
    sharingType: 'Single AC',
    status: 'Occupied',
    totalBeds: 1,
    occupiedBeds: 1,
    vacantBeds: 0,
    rentPerMonth: 9500,
    facilities: ['AC', 'Attached Bath', 'Wi-Fi'],
    residents: [
      { name: 'Vikram Singh', phone: '+91 98765 43222', checkInDate: '2025-08-01', course: 'Ph.D Biotech' },
    ],
  },
  {
    id: 'r302',
    roomNumber: '302',
    floor: '3rd Floor',
    sharingType: 'Double Attached',
    status: 'Occupied',
    totalBeds: 2,
    occupiedBeds: 2,
    vacantBeds: 0,
    rentPerMonth: 6500,
    facilities: ['Attached Bath', 'Wi-Fi'],
    residents: [
      { name: 'Rahul Gupta', phone: '+91 98765 43223', checkInDate: '2025-08-05', course: 'B.Tech IT' },
      { name: 'Gaurav Kumar', phone: '+91 98765 43224', checkInDate: '2025-08-08', course: 'B.Tech Mechanical' },
    ],
  },
  {
    id: 'r303',
    roomNumber: '303',
    floor: '3rd Floor',
    sharingType: 'Triple Shared',
    status: 'Partially Occupied',
    totalBeds: 3,
    occupiedBeds: 2,
    vacantBeds: 1,
    rentPerMonth: 5000,
    facilities: ['Common Bath', 'Wi-Fi'],
    residents: [
      { name: 'Sanjay Dutt', phone: '+91 98765 43225', checkInDate: '2025-08-02', course: 'BA English' },
      { name: 'Prateek Sen', phone: '+91 98765 43226', checkInDate: '2025-08-03', course: 'BA History' },
    ],
  },
  {
    id: 'r304',
    roomNumber: '304',
    floor: '3rd Floor',
    sharingType: 'Double Attached',
    status: 'Vacant',
    totalBeds: 2,
    occupiedBeds: 0,
    vacantBeds: 2,
    rentPerMonth: 6500,
    facilities: ['Attached Bath', 'Wi-Fi'],
    residents: [],
  },
];

export const initialResidentRequests: ResidentRequest[] = [
  {
    id: 'req-01',
    residentName: 'Rohan Sharma',
    roomNumber: '102',
    type: 'Sick Meal',
    details: 'Requested light Khichdi and Curd for Lunch (suffering from mild fever).',
    status: 'Pending',
    date: '2026-07-28',
    priority: 'High',
    avatarBg: '#3b82f6',
  },
  {
    id: 'req-02',
    residentName: 'Aditya Patel',
    roomNumber: '202',
    type: 'Leave Request',
    details: 'Weekend home leave approval from Friday July 31 to Sunday Aug 2.',
    status: 'Approved',
    date: '2026-07-28',
    priority: 'Medium',
    avatarBg: '#10b981',
  },
  {
    id: 'req-03',
    residentName: 'Vikram Singh',
    roomNumber: '301',
    type: 'Maintenance',
    details: 'AC in Room 301 is leaking water onto study desk area.',
    status: 'Pending',
    date: '2026-07-27',
    priority: 'High',
    avatarBg: '#ef4444',
  },
  {
    id: 'req-04',
    residentName: 'Kunal Shah',
    roomNumber: '203',
    type: 'Room Request',
    details: 'Requested transfer from Room 203 (4-Sharing) to Room 102 (Double).',
    status: 'Pending',
    date: '2026-07-26',
    priority: 'Medium',
    avatarBg: '#8b5cf6',
  },
  {
    id: 'req-05',
    residentName: 'Rahul Gupta',
    roomNumber: '302',
    type: 'Complaint',
    details: 'Wi-Fi connection flickering on 3rd floor west wing.',
    status: 'Completed',
    date: '2026-07-25',
    priority: 'Low',
    avatarBg: '#f59e0b',
  },
  {
    id: 'req-06',
    residentName: 'Yash Paul',
    roomNumber: '104',
    type: 'Maintenance',
    details: 'Bathroom door latch broken in Room 104.',
    status: 'Approved',
    date: '2026-07-25',
    priority: 'Medium',
    avatarBg: '#06b6d4',
  },
  {
    id: 'req-07',
    residentName: 'Siddharth Rao',
    roomNumber: '101',
    type: 'Skip Meal',
    details: 'Skipping Sunday Dinner due to family get-together outside.',
    status: 'Completed',
    date: '2026-07-24',
    priority: 'Low',
    avatarBg: '#64748b',
  },
  {
    id: 'req-08',
    residentName: 'Nikhil Mehta',
    roomNumber: '104',
    type: 'Special Timing',
    details: 'Requesting early breakfast at 6:30 AM on exam day.',
    status: 'Rejected',
    date: '2026-07-23',
    priority: 'Low',
    avatarBg: '#ec4899',
  },
];

export const initialFeeTransactions: FeeTransaction[] = [
  {
    id: 'ft-101',
    studentName: 'Rohit Verma',
    roomNumber: '105',
    month: 'July 2026',
    amount: 12500,
    amountPaid: 8000,
    dues: 4500,
    status: 'Partial',
    date: '2026-07-26',
    uploadedDate: '26 Jul, 08:30 am',
    lastPaymentDate: '26 Jul 2026',
    paymentMethod: 'UPI / GPay',
    phone: '+91 98765 43210',
    history: [
      { id: 'h-1', date: '2026-07-26', amountPaid: 8000, paymentMethod: 'UPI / GPay', receiptNo: 'REC-2026-0781' }
    ],
    monthlyRecords: [
      {
        id: 'mr-101-jul',
        monthName: 'July 2026',
        isCurrentMonth: true,
        dateRange: '01-07-2026 to 31-07-2026',
        amount: 12500,
        amountPaid: 8000,
        dues: 4500,
        status: 'Partial',
        lastPaymentDate: '26 Jul 2026',
        history: [{ id: 'h-1', date: '2026-07-26', amountPaid: 8000, paymentMethod: 'UPI / GPay', receiptNo: 'REC-2026-0781' }]
      },
      {
        id: 'mr-101-jun',
        monthName: 'June 2026',
        isCurrentMonth: false,
        dateRange: '01-06-2026 to 30-06-2026',
        amount: 12500,
        amountPaid: 12500,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '28 Jun 2026',
        history: [{ id: 'h-101-jun', date: '2026-06-28', amountPaid: 12500, paymentMethod: 'UPI', receiptNo: 'REC-2026-0611' }]
      },
      {
        id: 'mr-101-may',
        monthName: 'May 2026',
        isCurrentMonth: false,
        dateRange: '01-05-2026 to 31-05-2026',
        amount: 12500,
        amountPaid: 12500,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '25 May 2026',
        history: [{ id: 'h-101-may', date: '2026-05-25', amountPaid: 12500, paymentMethod: 'Cash', receiptNo: 'REC-2026-0504' }]
      }
    ]
  },
  {
    id: 'ft-102',
    studentName: 'Manish Pandey',
    roomNumber: '208',
    month: 'July 2026',
    amount: 10000,
    amountPaid: 0,
    dues: 10000,
    status: 'Pending',
    date: '2026-07-25',
    uploadedDate: '25 Jul, 08:15 pm',
    lastPaymentDate: '25 Jun 2026',
    phone: '+91 98765 43212',
    history: [],
    monthlyRecords: [
      {
        id: 'mr-102-jul',
        monthName: 'July 2026',
        isCurrentMonth: true,
        dateRange: '01-07-2026 to 31-07-2026',
        amount: 10000,
        amountPaid: 0,
        dues: 10000,
        status: 'Pending',
        lastPaymentDate: 'None',
        history: []
      },
      {
        id: 'mr-102-jun',
        monthName: 'June 2026',
        isCurrentMonth: false,
        dateRange: '01-06-2026 to 30-06-2026',
        amount: 10000,
        amountPaid: 10000,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '25 Jun 2026',
        history: [{ id: 'h-102-jun', date: '2026-06-25', amountPaid: 10000, paymentMethod: 'UPI', receiptNo: 'REC-2026-0650' }]
      }
    ]
  },
  {
    id: 'ft-103',
    studentName: 'Rahul Dravid',
    roomNumber: '103',
    month: 'July 2026',
    amount: 11000,
    amountPaid: 0,
    dues: 11000,
    status: 'Pending',
    date: '2026-07-27',
    uploadedDate: '27 Jul, 09:15 am',
    lastPaymentDate: '27 May 2026',
    phone: '+91 98765 43213',
    history: [],
    monthlyRecords: [
      {
        id: 'mr-103-jul',
        monthName: 'July 2026',
        isCurrentMonth: true,
        dateRange: '01-07-2026 to 31-07-2026',
        amount: 11000,
        amountPaid: 0,
        dues: 11000,
        status: 'Pending',
        lastPaymentDate: 'None',
        history: []
      },
      {
        id: 'mr-103-jun',
        monthName: 'June 2026',
        isCurrentMonth: false,
        dateRange: '01-06-2026 to 30-06-2026',
        amount: 11000,
        amountPaid: 5000,
        dues: 6000,
        status: 'Partial',
        lastPaymentDate: '15 Jun 2026',
        history: [{ id: 'h-103-jun', date: '2026-06-15', amountPaid: 5000, paymentMethod: 'Cash', receiptNo: 'REC-2026-0630' }]
      }
    ]
  },
  {
    id: 'ft-104',
    studentName: 'Vikram Singh',
    roomNumber: '301',
    month: 'July 2026',
    amount: 9500,
    amountPaid: 4500,
    dues: 5000,
    status: 'Overdue',
    date: '2026-07-10',
    uploadedDate: '10 Jul, 02:20 pm',
    lastPaymentDate: '10 Jul 2026',
    paymentMethod: 'Cash',
    phone: '+91 98765 43222',
    history: [
      { id: 'h-2', date: '2026-07-10', amountPaid: 4500, paymentMethod: 'Cash', receiptNo: 'REC-2026-0512' }
    ],
    monthlyRecords: [
      {
        id: 'mr-104-jul',
        monthName: 'July 2026',
        isCurrentMonth: true,
        dateRange: '01-07-2026 to 31-07-2026',
        amount: 9500,
        amountPaid: 4500,
        dues: 5000,
        status: 'Partial',
        lastPaymentDate: '10 Jul 2026',
        history: [{ id: 'h-2', date: '2026-07-10', amountPaid: 4500, paymentMethod: 'Cash', receiptNo: 'REC-2026-0512' }]
      },
      {
        id: 'mr-104-jun',
        monthName: 'June 2026',
        isCurrentMonth: false,
        dateRange: '01-06-2026 to 30-06-2026',
        amount: 9500,
        amountPaid: 9500,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '02 Jun 2026',
        history: [{ id: 'h-104-jun', date: '2026-06-02', amountPaid: 9500, paymentMethod: 'UPI', receiptNo: 'REC-2026-0602' }]
      }
    ]
  },
  {
    id: 'ft-105',
    studentName: 'Aditya Patel',
    roomNumber: '202',
    month: 'July 2026',
    amount: 8500,
    amountPaid: 8500,
    dues: 0,
    status: 'Paid',
    date: '2026-07-05',
    uploadedDate: '05 Jul, 11:45 am',
    lastPaymentDate: '05 Jul 2026',
    paymentMethod: 'Credit Card',
    phone: '+91 98765 43217',
    history: [
      { id: 'h-3', date: '2026-07-05', amountPaid: 8500, paymentMethod: 'Credit Card', receiptNo: 'REC-2026-0422' }
    ],
    monthlyRecords: [
      {
        id: 'mr-105-jul',
        monthName: 'July 2026',
        isCurrentMonth: true,
        dateRange: '01-07-2026 to 31-07-2026',
        amount: 8500,
        amountPaid: 8500,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '05 Jul 2026',
        history: [{ id: 'h-3', date: '2026-07-05', amountPaid: 8500, paymentMethod: 'Credit Card', receiptNo: 'REC-2026-0422' }]
      },
      {
        id: 'mr-105-jun',
        monthName: 'June 2026',
        isCurrentMonth: false,
        dateRange: '01-06-2026 to 30-06-2026',
        amount: 8500,
        amountPaid: 8500,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '04 Jun 2026',
        history: [{ id: 'h-105-jun', date: '2026-06-04', amountPaid: 8500, paymentMethod: 'UPI', receiptNo: 'REC-2026-0604' }]
      }
    ]
  },
  {
    id: 'ft-106',
    studentName: 'Sanjay Dutt',
    roomNumber: '303',
    month: 'July 2026',
    amount: 7500,
    amountPaid: 7500,
    dues: 0,
    status: 'Paid',
    date: '2026-07-03',
    uploadedDate: '03 Jul, 10:10 am',
    lastPaymentDate: '03 Jul 2026',
    paymentMethod: 'UPI',
    phone: '+91 98765 43225',
    history: [
      { id: 'h-4', date: '2026-07-03', amountPaid: 7500, paymentMethod: 'UPI', receiptNo: 'REC-2026-0399' }
    ],
    monthlyRecords: [
      {
        id: 'mr-106-jul',
        monthName: 'July 2026',
        isCurrentMonth: true,
        dateRange: '01-07-2026 to 31-07-2026',
        amount: 7500,
        amountPaid: 7500,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '03 Jul 2026',
        history: [{ id: 'h-4', date: '2026-07-03', amountPaid: 7500, paymentMethod: 'UPI', receiptNo: 'REC-2026-0399' }]
      }
    ]
  },
  {
    id: 'ft-107',
    studentName: 'Priya Sharma',
    roomNumber: '402',
    month: 'July 2026',
    amount: 9000,
    amountPaid: 0,
    dues: 9000,
    status: 'Pending',
    date: '2026-07-28',
    uploadedDate: '28 Jul, 04:30 pm',
    lastPaymentDate: '20 May 2026',
    phone: '+91 98765 43299',
    history: [],
    monthlyRecords: [
      {
        id: 'mr-107-jul',
        monthName: 'July 2026',
        isCurrentMonth: true,
        dateRange: '01-07-2026 to 31-07-2026',
        amount: 9000,
        amountPaid: 0,
        dues: 9000,
        status: 'Pending',
        lastPaymentDate: 'None',
        history: []
      },
      {
        id: 'mr-107-jun',
        monthName: 'June 2026',
        isCurrentMonth: false,
        dateRange: '01-06-2026 to 30-06-2026',
        amount: 9000,
        amountPaid: 9000,
        dues: 0,
        status: 'Paid',
        lastPaymentDate: '01 Jun 2026',
        history: [{ id: 'h-107-jun', date: '2026-06-01', amountPaid: 9000, paymentMethod: 'UPI', receiptNo: 'REC-2026-0601' }]
      }
    ]
  }
];

export const initialActivities: ActivityItem[] = [
  {
    id: 'act-1',
    time: '10m ago',
    title: 'New Check-in Registered',
    description: 'Dr. Ananya Roy assigned to Room 103 (Single AC).',
    category: 'checkin',
  },
  {
    id: 'act-2',
    time: '35m ago',
    title: 'Sick Meal Request Received',
    description: 'Rohan Sharma (Room 102) requested Light Khichdi for lunch.',
    category: 'request',
  },
  {
    id: 'act-3',
    time: '2h ago',
    title: 'Fee Payment Received',
    description: '₹6,500 received via UPI from Aditya Patel (Room 202).',
    category: 'payment',
  },
  {
    id: 'act-4',
    time: '4h ago',
    title: 'Maintenance Marked Done',
    description: 'Bathroom latch repair in Room 104 resolved by Warden.',
    category: 'maintenance',
  },
];
